sudo: required
language: python
dist: xenial
python:
  - "2.7"
  - "3.6"
  - "3.7"
install:
  - pip install codecov coverage
  - python setup.py bdist_wheel
  - pip install ./dist/tox_travis-*.whl
script: tox --installpkg ./dist/tox_travis-*.whl
after_success: coverage combine && codecov